import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "todoServices",
  description: "Generated by create todoServices",
  keywords: "react, React.js, Next.js, TailwindCSS, HTML, css",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>
          <Header />
          <main>
            <Providers> {children}</Providers>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
